#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
README="$SCRIPT_DIR/README.md"

{
  cat <<'HEADER'
# Catalog Test Cases

> Auto-generated by `generate_readme.sh` — do not edit manually.
>
> Run `bash tests/catalog/generate_readme.sh` to regenerate.

throw-trace が対応すべきパターンを網羅したカタログテスト集。
`cases/` 配下は同期前の `before.ts` に `fix` を適用し、`expected.ts` との完全一致と
2回目の `fix` が不変であることを検証する。直下の `.ts` は従来カタログとして、
宣言漏れがないことを継続確認する。

## Summary

| # | File | Description |
|---|------|-------------|
HEADER

  for f in "$SCRIPT_DIR"/*.ts; do
    basename=$(basename "$f")
    num="${basename%%_*}"
    description=$(head -1 "$f" | sed 's|^// *||')
    anchor=$(echo "$basename" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]//g')
    printf "| %s | [%s](#%s) | %s |\n" "$num" "$basename" "$anchor" "$description"
  done

  echo ""
  echo "## Sync Golden Cases"
  echo ""
  echo "| Case | Status | Description |"
  echo "|------|--------|-------------|"

  for case_dir in "$SCRIPT_DIR"/cases/*; do
    [ -d "$case_dir" ] || continue
    case_name=$(basename "$case_dir")
    description=$(sed -n 's/^description = "\(.*\)"$/\1/p' "$case_dir/case.toml")
    status=$(sed -n 's/^status = "\(.*\)"$/\1/p' "$case_dir/case.toml")
    printf "| [%s](#sync-%s) | %s | %s |\n" "$case_name" "$case_name" "$status" "$description"
  done

  echo ""
  echo "---"
  echo ""
  echo "## Details"
  echo ""

  for f in "$SCRIPT_DIR"/*.ts; do
    basename=$(basename "$f")
    description=$(head -1 "$f" | sed 's|^// *||')

    echo "### ${basename}"
    echo ""
    echo "${description}"
    echo ""
    echo '```typescript'
    cat "$f"
    echo '```'
    echo ""
  done

  echo "---"
  echo ""
  echo "## Sync Golden Case Details"
  echo ""

  for case_dir in "$SCRIPT_DIR"/cases/*; do
    [ -d "$case_dir" ] || continue
    case_name=$(basename "$case_dir")
    description=$(sed -n 's/^description = "\(.*\)"$/\1/p' "$case_dir/case.toml")

    echo "### Sync ${case_name}"
    echo ""
    echo "$description"
    echo ""
    echo "#### Before"
    echo ""
    echo '```typescript'
    cat "$case_dir/before.ts"
    echo '```'
    echo ""
    echo "#### Expected"
    echo ""
    echo '```typescript'
    cat "$case_dir/expected.ts"
    echo '```'
    echo ""
  done
} > "$README"

echo "Generated: $README"
