#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
README="$SCRIPT_DIR/README.md"

{
  cat <<'HEADER'
# Catalog Test Cases

> Auto-generated by `generate_readme.sh` — do not edit manually.
>
> Run `bash tests/catalog/generate_readme.sh` to regenerate.

throw-trace が対応すべきパターンを網羅したカタログテスト集。
各ファイルは「期待される `@throws` アノテーション付きの TypeScript コード」そのものであり、
ツールの出力と diff を取ることで正しさを検証する。

## Summary

| # | File | Description |
|---|------|-------------|
HEADER

  for f in "$SCRIPT_DIR"/*.ts; do
    basename=$(basename "$f")
    num="${basename%%_*}"
    description=$(head -1 "$f" | sed 's|^// *||')
    anchor=$(echo "$basename" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9_-]//g')
    printf "| %s | [%s](#%s) | %s |\n" "$num" "$basename" "$anchor" "$description"
  done

  echo ""
  echo "---"
  echo ""
  echo "## Details"
  echo ""

  for f in "$SCRIPT_DIR"/*.ts; do
    basename=$(basename "$f")
    description=$(head -1 "$f" | sed 's|^// *||')

    echo "### ${basename}"
    echo ""
    echo "${description}"
    echo ""
    echo '```typescript'
    cat "$f"
    echo '```'
    echo ""
  done
} > "$README"

echo "Generated: $README"
